### PR TITLE
Inline build for ParaView scene export

### PR DESCRIPTION
**Pull request by Lgt2x**
Add a `build:inline` npm script that builds Glance with all assets inlined, so that the bundled HTML file is standalone and can be used for the ParaView [scene export to VTKJS](https://www.kitware.com/exporting-paraview-scenes-to-paraview-glance/). This mimics the build behavior we had in Glance 4.17 before the Webpack 5 migration.

cc @mwestphal

### CODE REVIEW

**Comment by Lgt2x** [comment]
@floryst @bourdaisj

**Review by floryst — COMMENTED** [review]
LGTM!

One small note: we might as well merge the `build:inline` and `bundle` scripts to simplify things. Separating the two stages doesn't have any use-case as far as I'm concerned.

**Comment by Lgt2x** [comment]
`bundle` is also used after `build:release` in the Github action script https://github.com/Kitware/glance/blob/master/.github/workflows/publish.yml#L29

**Comment by floryst** [comment]
I suppose that does add a `ParaViewGlance.html` to the output bundle, but since it is currently it's kind of broken anyways I'm okay with removing that step in the publish workflow.

**Comment by Lgt2x** [comment]
`build:inline` and `bundle` merged

**Comment by floryst** [comment]
LGTM. Thanks!

**Pull request merged**
